CC = gcc

# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -g -Wall

# the build target executable:
ww = myprog

all: $ww

$ww: $ww.c
    $(CC) $(CFLAGS) -o $ww $ww.c

clean:
    $(RM) $ww